### PR TITLE
corrected some typos

### PR DESCRIPTION
**Pull request by antialias**

### CODE REVIEW

**Comment by antialias** [comment]
@hellatan I don't see a way to assign this to you for merging

**Comment by hellatan** [comment]
i'm not in the drop down to the right under "Assignee"?

**Comment by hellatan** [comment]
also commit the static PROD output - `npm run build`

**Comment by hellatan** [comment]
ah, i think i see - you may have to go to my repo (not your fork) itself to give it an assignee.

**Comment by antialias** [comment]
> also commit the static PROD output - `npm run build`

Ewww. I think not having to do this is a good argument [for using Jekyll](https://help.github.com/articles/using-jekyll-with-pages/) until we can get an auto build system for metalsmith. Github does the builds automatically.

**Comment by antialias** [comment]
> ah, i think i see - you may have to go to my repo (not your fork) itself to give it an assignee.

I think you have to add me as a contributor.

**Comment by hellatan** [comment]
we can't use custom [plugins for github pages](http://jekyllrb.com/docs/plugins/):

> Plugins on GitHub Pages
> GitHub Pages is powered by Jekyll. However, all Pages sites are generated using the --safe option to disable custom plugins for security reasons. Unfortunately, this means your plugins won’t work if you’re deploying to GitHub Pages.
> You can still use GitHub Pages to publish your site, but you’ll need to convert the site locally and push the generated static files to your GitHub repository instead of the Jekyll source files.

so if we did want to do custom plugins for whatever reason (like ones from [this list](http://jekyllrb.com/docs/plugins/#generators-1)), we'd still need to do a build step with jekyll and then commit those changed files.

I would think that having the flexibility to make the blog more extensible as we see fit should also be a top consideration. 

Maybe another solution is that PROD output is always done when developing locally so then you will see additional files changed when doing your commit?

**Comment by hellatan** [comment]
@antialias you should be a contributor now

**Comment by hellatan** [comment]
> Maybe another solution is that PROD output is always done when developing locally so then you will see additional files changed when doing your commit?

doing a preliminary modification to the `build.js` file only allows fro livereload in the browser but does not go through the metalsmith `build` step so some further investigation would be needed.

**Comment by hellatan** [comment]
PR with preliminary "always publish" functionality - https://github.com/hellatan/hellatan.github.io/pull/3

**Comment by antialias** [comment]
Static pages have been rebuilt. Please merge soon; the grammar mistakes and typos that this PR corrects are rather embarrassing. Thx.

**Pull request merged**
